version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/react-vite-boilerplate
    ports:
      - '3000:3000'
    expose:
      - '3000'
  # unit:
  #   depends_on:
  #     - web
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile
  #   command: npm test
  e2e:
    links:
      - web
    depends_on:
      - web
      # - unit
    build: 
      context: ./
      dockerfile: Dockerfile
    command: npm run cy:run
    

  # e2e:
  #   depends_on:
  #     - web
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile.e2e
    # command: npm run cy:run
    